### PR TITLE
add client side api

### PR DESCRIPTION
**Pull request by brittanyjspringer**

### CODE REVIEW

**Comment by psarson** [comment]
Still working on it, a few other bugs popped up as well.

**Comment by brittanyjspringer** [comment]
Cool, please chat me on Checkpoint #7 if I can help at all. Happy to look further tomorrow night too.

**Comment by psarson** [comment]
I think I'm gonna hack away at it - unless you see something in the gist

https://gist.github.com/psarson/2a16d02c393d27cb7f6d04f3fec9d7ff

**Comment by brittanyjspringer** [comment]
The gist looks correct. If you want to make sure all of the tests are working, we can work through the Javascript permissions tomorrow night.

**Comment by psarson** [comment]
Cool - looking forward to it!

**Comment by brittanyjspringer** [comment]
@psarson please make sure to push the last changes up to this branch so I can check you off!

**Pull request merged**
